// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type AddRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type DeleteRequest struct {
	Id int `path:"id"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code int    `json:"code"`
	Data string `json:"data"`
	Msg  string `json:"msg"`
}

type QueryRequest struct {
	Id int `path:"id"`
}

type UpdateRequest struct {
	Id       int    `json:"id"`
	UserName string `json:"userName"`
	Password string `json:"password"`
}
