// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/hellodemo.proto

package hellodemo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hellodemo service

func NewHellodemoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hellodemo service

type HellodemoService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hellodemo_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Hellodemo_PingPongService, error)
}

type hellodemoService struct {
	c    client.Client
	name string
}

func NewHellodemoService(name string, c client.Client) HellodemoService {
	return &hellodemoService{
		c:    c,
		name: name,
	}
}

func (c *hellodemoService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Hellodemo.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hellodemoService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Hellodemo_StreamService, error) {
	req := c.c.NewRequest(c.name, "Hellodemo.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &hellodemoServiceStream{stream}, nil
}

type Hellodemo_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type hellodemoServiceStream struct {
	stream client.Stream
}

func (x *hellodemoServiceStream) Close() error {
	return x.stream.Close()
}

func (x *hellodemoServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellodemoServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellodemoServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellodemoServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hellodemoService) PingPong(ctx context.Context, opts ...client.CallOption) (Hellodemo_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Hellodemo.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &hellodemoServicePingPong{stream}, nil
}

type Hellodemo_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type hellodemoServicePingPong struct {
	stream client.Stream
}

func (x *hellodemoServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *hellodemoServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *hellodemoServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellodemoServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellodemoServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *hellodemoServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hellodemo service

type HellodemoHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Hellodemo_StreamStream) error
	PingPong(context.Context, Hellodemo_PingPongStream) error
}

func RegisterHellodemoHandler(s server.Server, hdlr HellodemoHandler, opts ...server.HandlerOption) error {
	type hellodemo interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Hellodemo struct {
		hellodemo
	}
	h := &hellodemoHandler{hdlr}
	return s.Handle(s.NewHandler(&Hellodemo{h}, opts...))
}

type hellodemoHandler struct {
	HellodemoHandler
}

func (h *hellodemoHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.HellodemoHandler.Call(ctx, in, out)
}

func (h *hellodemoHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HellodemoHandler.Stream(ctx, m, &hellodemoStreamStream{stream})
}

type Hellodemo_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type hellodemoStreamStream struct {
	stream server.Stream
}

func (x *hellodemoStreamStream) Close() error {
	return x.stream.Close()
}

func (x *hellodemoStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellodemoStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellodemoStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellodemoStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *hellodemoHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.HellodemoHandler.PingPong(ctx, &hellodemoPingPongStream{stream})
}

type Hellodemo_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type hellodemoPingPongStream struct {
	stream server.Stream
}

func (x *hellodemoPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *hellodemoPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hellodemoPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hellodemoPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hellodemoPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *hellodemoPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
