// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.4
// source: article.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------Custer--------------------------------
type Custer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`      //Id
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`   //鍚嶅瓧
	Age   int64  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`    //骞撮緞
	Phone string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"` //鐢佃瘽
	Emil  string `protobuf:"bytes,5,opt,name=Emil,proto3" json:"Emil,omitempty"`   //閭欢
	City  string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`   //鍩庡競
}

func (x *Custer) Reset() {
	*x = Custer{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custer) ProtoMessage() {}

func (x *Custer) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custer.ProtoReflect.Descriptor instead.
func (*Custer) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *Custer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Custer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Custer) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Custer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Custer) GetEmil() string {
	if x != nil {
		return x.Emil
	}
	return ""
}

func (x *Custer) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type AddCusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`      //Id
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`   //鍚嶅瓧
	Age   int64  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`    //骞撮緞
	Phone string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"` //鐢佃瘽
	Emil  string `protobuf:"bytes,5,opt,name=Emil,proto3" json:"Emil,omitempty"`   //閭欢
	City  string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`   //鍩庡競
}

func (x *AddCusterReq) Reset() {
	*x = AddCusterReq{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCusterReq) ProtoMessage() {}

func (x *AddCusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCusterReq.ProtoReflect.Descriptor instead.
func (*AddCusterReq) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *AddCusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddCusterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCusterReq) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AddCusterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddCusterReq) GetEmil() string {
	if x != nil {
		return x.Emil
	}
	return ""
}

func (x *AddCusterReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type AddCusterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`    //msg
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` //code
	Id   string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`      //id
}

func (x *AddCusterResp) Reset() {
	*x = AddCusterResp{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCusterResp) ProtoMessage() {}

func (x *AddCusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCusterResp.ProtoReflect.Descriptor instead.
func (*AddCusterResp) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *AddCusterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddCusterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddCusterResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`      //Id
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`   //鍚嶅瓧
	Age   int64  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`    //骞撮緞
	Phone string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"` //鐢佃瘽
	Emil  string `protobuf:"bytes,5,opt,name=Emil,proto3" json:"Emil,omitempty"`   //閭欢
	City  string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`   //鍩庡競
}

func (x *UpdateCusterReq) Reset() {
	*x = UpdateCusterReq{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCusterReq) ProtoMessage() {}

func (x *UpdateCusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCusterReq.ProtoReflect.Descriptor instead.
func (*UpdateCusterReq) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCusterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCusterReq) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateCusterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateCusterReq) GetEmil() string {
	if x != nil {
		return x.Emil
	}
	return ""
}

func (x *UpdateCusterReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type UpdateCusterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`    //msg
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` //code
}

func (x *UpdateCusterResp) Reset() {
	*x = UpdateCusterResp{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCusterResp) ProtoMessage() {}

func (x *UpdateCusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCusterResp.ProtoReflect.Descriptor instead.
func (*UpdateCusterResp) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCusterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UpdateCusterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DelCusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *DelCusterReq) Reset() {
	*x = DelCusterReq{}
	mi := &file_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCusterReq) ProtoMessage() {}

func (x *DelCusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCusterReq.ProtoReflect.Descriptor instead.
func (*DelCusterReq) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{5}
}

func (x *DelCusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelCusterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`    //msg
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` //code
}

func (x *DelCusterResp) Reset() {
	*x = DelCusterResp{}
	mi := &file_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCusterResp) ProtoMessage() {}

func (x *DelCusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCusterResp.ProtoReflect.Descriptor instead.
func (*DelCusterResp) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{6}
}

func (x *DelCusterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DelCusterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetCusterByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *GetCusterByIdReq) Reset() {
	*x = GetCusterByIdReq{}
	mi := &file_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCusterByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCusterByIdReq) ProtoMessage() {}

func (x *GetCusterByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCusterByIdReq.ProtoReflect.Descriptor instead.
func (*GetCusterByIdReq) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{7}
}

func (x *GetCusterByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCusterByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Custer *Custer `protobuf:"bytes,1,opt,name=custer,proto3" json:"custer,omitempty"` //custer
}

func (x *GetCusterByIdResp) Reset() {
	*x = GetCusterByIdResp{}
	mi := &file_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCusterByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCusterByIdResp) ProtoMessage() {}

func (x *GetCusterByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCusterByIdResp.ProtoReflect.Descriptor instead.
func (*GetCusterByIdResp) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{8}
}

func (x *GetCusterByIdResp) GetCuster() *Custer {
	if x != nil {
		return x.Custer
	}
	return nil
}

type SearchCusterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   //page
	Limit int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` //limit
	Id    int64  `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`       //Id
	Name  string `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`    //鍚嶅瓧
	Age   int64  `protobuf:"varint,5,opt,name=Age,proto3" json:"Age,omitempty"`     //骞撮緞
	Phone string `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`  //鐢佃瘽
	Emil  string `protobuf:"bytes,7,opt,name=Emil,proto3" json:"Emil,omitempty"`    //閭欢
	City  string `protobuf:"bytes,8,opt,name=City,proto3" json:"City,omitempty"`    //鍩庡競
}

func (x *SearchCusterReq) Reset() {
	*x = SearchCusterReq{}
	mi := &file_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCusterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCusterReq) ProtoMessage() {}

func (x *SearchCusterReq) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCusterReq.ProtoReflect.Descriptor instead.
func (*SearchCusterReq) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCusterReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchCusterReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCusterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchCusterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchCusterReq) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *SearchCusterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SearchCusterReq) GetEmil() string {
	if x != nil {
		return x.Emil
	}
	return ""
}

func (x *SearchCusterReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type SearchCusterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Custer []*Custer `protobuf:"bytes,1,rep,name=custer,proto3" json:"custer,omitempty"` //custer
}

func (x *SearchCusterResp) Reset() {
	*x = SearchCusterResp{}
	mi := &file_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCusterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCusterResp) ProtoMessage() {}

func (x *SearchCusterResp) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCusterResp.ProtoReflect.Descriptor instead.
func (*SearchCusterResp) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCusterResp) GetCuster() []*Custer {
	if x != nil {
		return x.Custer
	}
	return nil
}

var File_article_proto protoreflect.FileDescriptor

var file_article_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x7c, 0x0a, 0x06, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x41, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x45, 0x6d, 0x69,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x45, 0x6d, 0x69, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74,
	0x79, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x45, 0x6d, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x45, 0x6d,
	0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x22, 0x45, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x85, 0x01,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x45, 0x6d, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x45, 0x6d, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x43, 0x69, 0x74, 0x79, 0x22, 0x38, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x1e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x35, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x06, 0x63, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x22, 0xaf, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x45, 0x6d, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x45, 0x6d, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x43, 0x69, 0x74, 0x79, 0x22, 0x36, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x65, 0x72, 0x32, 0xa1, 0x02,
	0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x41, 0x64, 0x64,
	0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x43,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64,
	0x64, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x43, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData = file_article_proto_rawDesc
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_article_proto_rawDescData)
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_article_proto_goTypes = []any{
	(*Custer)(nil),            // 0: pb.Custer
	(*AddCusterReq)(nil),      // 1: pb.AddCusterReq
	(*AddCusterResp)(nil),     // 2: pb.AddCusterResp
	(*UpdateCusterReq)(nil),   // 3: pb.UpdateCusterReq
	(*UpdateCusterResp)(nil),  // 4: pb.UpdateCusterResp
	(*DelCusterReq)(nil),      // 5: pb.DelCusterReq
	(*DelCusterResp)(nil),     // 6: pb.DelCusterResp
	(*GetCusterByIdReq)(nil),  // 7: pb.GetCusterByIdReq
	(*GetCusterByIdResp)(nil), // 8: pb.GetCusterByIdResp
	(*SearchCusterReq)(nil),   // 9: pb.SearchCusterReq
	(*SearchCusterResp)(nil),  // 10: pb.SearchCusterResp
}
var file_article_proto_depIdxs = []int32{
	0,  // 0: pb.GetCusterByIdResp.custer:type_name -> pb.Custer
	0,  // 1: pb.SearchCusterResp.custer:type_name -> pb.Custer
	1,  // 2: pb.article.AddCuster:input_type -> pb.AddCusterReq
	3,  // 3: pb.article.UpdateCuster:input_type -> pb.UpdateCusterReq
	5,  // 4: pb.article.DelCuster:input_type -> pb.DelCusterReq
	7,  // 5: pb.article.GetCusterById:input_type -> pb.GetCusterByIdReq
	9,  // 6: pb.article.SearchCuster:input_type -> pb.SearchCusterReq
	2,  // 7: pb.article.AddCuster:output_type -> pb.AddCusterResp
	4,  // 8: pb.article.UpdateCuster:output_type -> pb.UpdateCusterResp
	6,  // 9: pb.article.DelCuster:output_type -> pb.DelCusterResp
	8,  // 10: pb.article.GetCusterById:output_type -> pb.GetCusterByIdResp
	10, // 11: pb.article.SearchCuster:output_type -> pb.SearchCusterResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_article_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_rawDesc = nil
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
