// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"gosql2pb/internal/logic"
	"gosql2pb/internal/svc"
	"gosql2pb/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

// -----------------------Custer-----------------------
func (s *ArticleServer) AddCuster(ctx context.Context, in *pb.AddCusterReq) (*pb.AddCusterResp, error) {
	l := logic.NewAddCusterLogic(ctx, s.svcCtx)
	return l.AddCuster(in)
}

func (s *ArticleServer) UpdateCuster(ctx context.Context, in *pb.UpdateCusterReq) (*pb.UpdateCusterResp, error) {
	l := logic.NewUpdateCusterLogic(ctx, s.svcCtx)
	return l.UpdateCuster(in)
}

func (s *ArticleServer) DelCuster(ctx context.Context, in *pb.DelCusterReq) (*pb.DelCusterResp, error) {
	l := logic.NewDelCusterLogic(ctx, s.svcCtx)
	return l.DelCuster(in)
}

func (s *ArticleServer) GetCusterById(ctx context.Context, in *pb.GetCusterByIdReq) (*pb.GetCusterByIdResp, error) {
	l := logic.NewGetCusterByIdLogic(ctx, s.svcCtx)
	return l.GetCusterById(in)
}

func (s *ArticleServer) SearchCuster(ctx context.Context, in *pb.SearchCusterReq) (*pb.SearchCusterResp, error) {
	l := logic.NewSearchCusterLogic(ctx, s.svcCtx)
	return l.SearchCuster(in)
}
