// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package handler

import (
	"net/http"

	"demo03/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/add",
				Handler: addHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/user/delete/:id",
				Handler: deleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/query/:id",
				Handler: queryHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/update",
				Handler: updateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
