// Code generated by goctl. DO NOT EDIT.
package types

type Article struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type GetArticleListReq struct {
}

type GetArticleListResp struct {
	Articles []Article `json:"Articles"`
}

type CreateArticleReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateArticleResp struct {
	Message string `json:"message"`
	Code    int    `json:"code"`
}

type DeleteArticleReq struct {
	Id int64 `json:"id"`
}

type DeleteArticleResp struct {
}

type UpdateArticleReq struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdateArticleResp struct {
}
